#find_package(qpid-proton-cpp REQUIRED)
#find_package(asio REQUIRED)
#find_package(s-ldm-components REQUIRED CONFIG COMPONENTS asn1 decoder-module options vehicle-visualizer)
find_package(Boost REQUIRED COMPONENTS)
find_package(cpprestsdk REQUIRED)
find_package(GeographicLib REQUIRED)
find_package(log4cplus REQUIRED CONFIG)
find_package(nlohmann_json REQUIRED CONFIG)
#find_package(qpid-proton REQIRED CONFIG)